### ISSUE TITLE
show error line in input bib file 

### ISSUE THREAD

**Issue by jpdeleon** [pcubillos/bibmanager#74]
I have a long list of ADS bib file but there are some incorrectly formatted entries that I like to fix. Is there a way `bibm` can point which line in the input file is causing trouble?

```shell
$ bibm cleanup ref.bib 

Traceback (most recent call last):
  File "/home/jp/miniconda3/envs/py3/bin/bibm", line 8, in <module>
    sys.exit(main())
  File "/home/jp/miniconda3/envs/py3/lib/python3.7/site-packages/bibmanager/__main__.py", line 1135, in main
    args.func(args)
  File "/home/jp/miniconda3/envs/py3/lib/python3.7/site-packages/bibmanager/__main__.py", line 201, in cli_cleanup
    bibs = bm.loadfile(args.bibfile)
  File "/home/jp/miniconda3/envs/py3/lib/python3.7/site-packages/bibmanager/bib_manager/bib_manager.py", line 556, in loadfile
    bibs = [Bib(entry, **meta) for entry,meta in zip(entries,meta_info)]
  File "/home/jp/miniconda3/envs/py3/lib/python3.7/site-packages/bibmanager/bib_manager/bib_manager.py", line 556, in <listcomp>
    bibs = [Bib(entry, **meta) for entry,meta in zip(entries,meta_info)]
  File "/home/jp/miniconda3/envs/py3/lib/python3.7/site-packages/bibmanager/bib_manager/bib_manager.py", line 135, in __init__
    raise ValueError(f'Invalid month value ({value})')
ValueError: Invalid month value (x)
```

**Comment by pcubillos** [comment]
Hi Jerome,
Yes, in this error message, the month field has an invalid value (the string 'x').  I'm guessing this is a custom-made entry.  The values in the month field should be one of: jan, feb, mar, etc., or could be a number between 1-12 or you could remove the month field entirely.

I'd recommend do a search and edit. To take a quick look on Linux/OSX you type:
```
find 'ref.bib' -exec grep 'month' {} \; -print
```

**Comment by pcubillos** [comment]
Hi! So, I think I'll close this issue.  Let me know if that was not the problem to re-open it, or open a new one if you are finding other issues.
